kind: pipeline
type: docker
name: default

steps:
- name: builing_ui
  image: node
  commands:
    - ls
    - npm install -g @angular/cli
    - npm install
    - ng build
    - ls
# to push docker image into ecr-repo
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    tags: [ latest, 1.0, 1 ]
    repo: 633025986259.dkr.ecr.us-east-1.amazonaws.com/wisereads-ui
    registry: 633025986259.dkr.ecr.us-east-1.amazonaws.com
  when:
    event: push
# Deploy to eks cluster
- name: deploy
  image: drone-eks-plugin:latest
  iam_role_arn: arn:aws:iam::633025986259:role/eks-role
  eks_cluster: eks-cluster
  namespace: default
  deployment: wisereads-ui
  repo: 633025986259.dkr.ecr.us-east-1.amazonaws.com/wisereads-ui
  container: wisereads-ui
  tag: latest
  when:
    branch: master
